Refactor cron-based heritrix jobs.

diff --git a/yulWA-yfile b/yulWA-yfile
--- a/yulWA-yfile
+++ b/yulWA-yfile
@@ -1,7 +1,25 @@
 #!/bin/bash
-# Bash script that archives selected York University web sites using the WARC ISO format.
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DATE=`date +"%Y_%m_%d"`
 
-/usr/bin/curl --silent -d "action=teardown" -k -u nruest:password --anyauth --location https://omega.library.yorku.ca:8983/engine/job/yfile && sleep 10 && /usr/bin/curl --silent -d "action=build" -k -u nruest:password --anyauth --location https://omega.library.yorku.ca:8983/engine/job/yfile && sleep 10 && /usr/bin/curl --silent -d "action=launch" -k -u nruest:password --anyauth --location https://omega.library.yorku.ca:8983/engine/job/yfile && sleep 10 && /usr/bin/curl --silent -d "action=unpause" -k -u nruest:password --anyauth --location https://omega.library.yorku.ca:8983/engine/job/yfile
-echo "$(date) - YFile archived" >> /var/log/heritrix/YFILE.log
+DATE=$(date +"%Y_%m_%d")
+URL="https://omega.library.yorku.ca:8983/engine/job/yfile"
+USERNAME="nruest"
+PASSWORD="password"
+LOG_FILE="/var/log/heritrix/YFILE.log"
+
+function start_crawl {
+    local action="$1"
+    /usr/bin/curl --silent -d "action=$action" -k -u "$USERNAME:$PASSWORD" --anyauth --location "$URL"
+    if [ $? -eq 0 ]; then
+        echo "[INFO] $(date) - $action started" >> "$LOG_FILE"
+    else
+        echo "[ERROR] $(date) - $action" >> "$LOG_FILE"
+    fi
+}
+
+start_crawl "teardown"
+sleep 10
+start_crawl "build"
+sleep 10
+start_crawl "launch"
+sleep 10
+start_crawl "unpause"
